version: "3.9"

networks:
  fieldops_net:
    name: fieldops_net

volumes:
  pg_data:
  mysql_data:
  mongo_data:
  localstack_data:

services:
  postgres:
    image: postgres:15
    container_name: fieldops_postgres
    environment:
      POSTGRES_USER: fieldops
      POSTGRES_PASSWORD: fieldops
      POSTGRES_DB: fieldops_auth
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U fieldops"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [fieldops_net]
    volumes:
      - pg_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: fieldops_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fieldops_jobs
      MYSQL_USER: fieldops
      MYSQL_PASSWORD: fieldops
    command: ["--default-authentication-plugin=mysql_native_password","--log_bin_trust_function_creators=1"]
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-uroot","-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [fieldops_net]
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: fieldops_mongo
    ports: ["27017:27017"]
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 20
    networks: [fieldops_net]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: fieldops_redis
    ports: ["6379:6379"]
    command: ["redis-server","--appendonly","no"]
    networks: [fieldops_net]

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fieldops_mailhog
    ports: ["1025:1025","8025:8025"] # SMTP on 1025, Web UI on 8025
    networks: [fieldops_net]

  localstack:
    image: localstack/localstack:latest
    container_name: fieldops_localstack
    environment:
      SERVICES: s3,sqs
      AWS_DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
      DOCKER_HOST: unix:///var/run/docker.sock
    ports: ["4566:4566"]
    networks: [fieldops_net]
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
