name: CI (PR)

on:
  pull_request:
    branches: [main]

jobs:
  gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      # --- new step: run tests with coverage (once you add tests) ---
      - name: Run tests with coverage
        run: npm test -- --coverage || echo "no tests yet"

      # --- upload coverage to Codecov ---
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # only required for private repos
          directory: ./gateway/coverage
